version: "3"

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./../src:/var/www/html
      - ./web/certs:/etc/nginx/ssl
      - ./web/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database
      - php-fpm
    links:
      - database
      - php-fpm
  php-fpm:
    container_name: php-fpm
    restart: unless-stopped
    build:
      context: ./../
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./../src/:/var/www/html
    depends_on:
      - database
    links:
      - database
  database:
    container_name: database
    restart: unless-stopped
    image: mysql:latest
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "6603:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p password" ]
      retries: 3
      timeout: 5s